#ifndef GUARD_CONSTANTS_P2_COMMANDS_H
#define GUARD_CONSTANTS_P2_COMMANDS_H

#define P2_CMD_QUEUE_SIZE 10

enum Player2Command
{
    P2_CMD_NONE = 0,
    P2_CMD_USE_FIELD_MOVE,
    P2_CMD_END_FIELD_MOVE,
    P2_CMD_PUSH_BOULDER,
    P2_CMD_USE_ROCK_SMASH,
    P2_CMD_USE_SURF,
    P2_CMD_END_USE_SURF,
    P2_CMD_STOP_SURFING,
    P2_CMD_END_STOP_SURFING,
    P2_CMD_USE_ROCK_CLIMB,
    P2_CMD_RIDE_ROCK_CLIMB,
    P2_CMD_BOB_ROCK_CLIMB,
    P2_CMD_JUMP_AFTER_ROCK_CLIMB,
    P2_CMD_END_USE_ROCK_CLIMB,
    P2_CMD_FACE_DIRECTION,
    P2_CMD_WALK_IN_PLACE,
    P2_CMD_WALK_IN_PLACE_FAST,
    P2_CMD_WALK_IN_PLACE_FASTER,
    P2_CMD_WALK_NORMAL,
    P2_CMD_WALK_FAST,
    P2_CMD_RUN,
    P2_CMD_JUMP,
    P2_CMD_JUMP_2,
    P2_CMD_RIDE_WATER_CURRENT,
    P2_CMD_ADD_OBJECT,
    P2_CMD_APPLY_MOVEMENT,
    P2_CMD_INSTANT_COMMANDS_START,
    P2_CMD_CONTROL_FLAG = P2_CMD_INSTANT_COMMANDS_START,
    P2_CMD_SET_INTERACTION_VAR,
    P2_CMD_INTERACT,
    P2_CMD_REQUEST_POSITION,
    P2_CMD_UPDATE_POSITION,
    P2_CMD_REMOVE_OBJECT,
    P2_CMD_MOVE_OBJECT,
    P2_CMD_END_DROP_HEAT_BADGE,
};

enum Player2Movement
{
    P2_MOVEMENT_NONE,
    P2_MOVEMENT_DIGLETT_DIG_DOWN,
    P2_MOVEMENT_MAGMA_GRUNT_M_CONFUSED,
    P2_MOVEMENT_DIGLETT_DIG_UP,
    P2_MOVEMENT_MAGMA_GRUNT_M_SURPRISED,
    P2_MOVEMENT_MAGMA_GRUNT_M_WATCH_BADGE_FALL_DOWN,
    P2_MOVEMENT_HEAT_BADGE_FALL_DOWN,
    P2_MOVEMENT_DIGLETT_ASK_NUMBER,
    P2_MOVEMENT_EXCLAMATION_MARK,
};

#endif  // GUARD_CONSTANTS_P2_COMMANDS_H
