#ifndef GUARD_CONSTANTS_P2_COMMANDS_H
#define GUARD_CONSTANTS_P2_COMMANDS_H

enum Player2Command
{
    P2_CMD_NONE = 0,
    P2_CMD_USE_FIELD_MOVE,
    P2_CMD_END_FIELD_MOVE,
    P2_CMD_PUSH_BOULDER,
    P2_CMD_USE_ROCK_SMASH,
    P2_CMD_END_ROCK_SMASH,
    P2_CMD_USE_SURF,
    P2_CMD_END_USE_SURF,
    P2_CMD_STOP_SURFING,
    P2_CMD_END_STOP_SURFING,
    P2_CMD_USE_ROCK_CLIMB,
    P2_CMD_RIDE_ROCK_CLIMB,
    P2_CMD_BOB_ROCK_CLIMB,
    P2_CMD_END_USE_ROCK_CLIMB,
    P2_CMD_FACE_DIRECTION,
    P2_CMD_WALK_IN_PLACE,
    P2_CMD_WALK_IN_PLACE_FAST,
    P2_CMD_WALK_IN_PLACE_FASTER,
    P2_CMD_WALK_NORMAL,
    P2_CMD_WALK_FAST,
    P2_CMD_RUN,
    P2_CMD_JUMP,
    P2_CMD_JUMP_2,
    P2_CMD_RIDE_WATER_CURRENT,
    P2_CMD_INSTANT_COMMANDS_START,
    P2_CMD_TRY_SAVE_AND_DISCONNECT = P2_CMD_INSTANT_COMMANDS_START,
    P2_CMD_CANCEL_SAVE,
    P2_CMD_REQUEST_POSITION,
    P2_CMD_UPDATE_POSITION,
};

#endif  // GUARD_CONSTANTS_P2_COMMANDS_H
