gText_Intro_Shelly_Welcome::
	.string "{SPEAKER NAME_SHELLY COLOR_AQUA}Hey, you!\p"
	.string "Next GRUNT in line, get over here!\p"
	.string "{FONT 5}(Sigh…)\p"
	.string "{FONT_NORMAL}Alright, so I've given this whole\n"
	.string "lecture way too many times today,\l"
	.string "so you get the TLDR.\p"
	.string "You're here at VOLCANO CANYON to clear\n"
	.string "a path in VOLCANO CAVERN so the main\l"
	.string "team {FONT 5}(me){FONT_NORMAL} can get through it easily.\p"
	.string "We've had reports of an unknown\n"
	.string "WATER-type LEGENDARY POKéMON\l"
	.string "causing a ruckus at the deepest\l"
	.string "part of the cave.\p"
	.string "Whatever you do, DO NOT approach it\n"
	.string "if you happen to run into it.\p"
	.string "That's for us ADMINS to handle.\p"
	.string "$"

gText_Intro_Shelly_MainSpeech::
	.string "{SPEAKER NAME_SHELLY COLOR_AQUA}We've had some problems with GRUNTS\n"
	.string "bringing their POOCHYENA to our\l"
	.string "EXTREMELY IMPORTANT missions.\p"
	.string "That STUPID KID keeps interfering\n"
	.string "with our plans because those GRUNTS\l"
	.string "aren't bringing enough WATER-types\l"
	.string "{FONT 5}(the best type) {FONT_NORMAL}with them.\p"
	.string "$"

gText_Intro_Shelly_MainSpeechPt2::
	.string "{SPEAKER NAME_SHELLY COLOR_AQUA}Oh yeah. We have a new… {FONT 5}ugh… {FONT_NORMAL}\p"
	.string "{MIN_LETTER_SPACING 2}P{PAUSE 3} R{PAUSE 3} O{PAUSE 3} T{PAUSE 3} O{PAUSE 3} C{PAUSE 3} O{PAUSE 3} L{PAUSE 3} .\p"
	.string "{MIN_LETTER_SPACING 0}{FONT 5}{AUTO_SCROLL 1}ok so i know that archie is under a LOT of\n"
	.string "stress right now with everything that\l"
	.string "happened last week but would it KILL him\l"
	.string "to not push a bunch of new orders on me\l"
	.string "while i'm trying to clean up HIS MESS??\l"
	.string "he acts like he owns the whole team!!!\l"
	.string "i mean i guess he technically does but i was\l"
	.string "supposed to get my VACATION this week and\l"
	.string "suddenly that's out the window because\l"
	.string "THERES TOO MUCH DAMN WATER IN DEWFORD!!!!!{PAUSE 40}\p"
	.string "{FONT_NORMAL}.{PAUSE 50}\n"
	.string ".{PAUSE 50}\l"
	.string "{AUTO_SCROLL 0}uh…\p"
	.string "Sorry you had to hear all that.\p"
	.string "All the damage control work for last\n"
	.string "week's incident with KYOGRE has been\l"
	.string "catastrophic for my sleep schedule.\p"
	.string "As I was TRYING to say, its now AQUA\n"
	.string "policy that you have to sign a waiver\l"
	.string "before any hazardous missions.\p"
	.string "\n"
	.string "$"

gText_Intro_Shelly_AndYouAre::
	.string "{SPEAKER NAME_SHELLY COLOR_AQUA}Let me know your name and gender\n"
	.string "and you'll be good to go.\p$"

gText_Intro_Shelly_BoyOrGirl::
	.string "Gender first, please.$"

gText_Intro_Shelly_WhatsYourName::
	.string "Perfect.\n"
	.string "And your name?$"

gText_Intro_Shelly_SoItsPlayer::
	.string "{SPEAKER NAME_SHELLY COLOR_AQUA}Just to make sure I have that right,\n"
	.string "it's {PLAYER}{KUN}?\p"
	.string "$"

gText_Intro_Shelly_YourePlayer::
	.string "{SPEAKER NAME_SHELLY COLOR_AQUA}Great, thanks.\n"
	.string "You're all set to go!\p"
	.string "$"

gText_Intro_Shelly_AreYouReady::
	.string "{SPEAKER NAME_SHELLY COLOR_AQUA}Hey, {PLAYER}{KUN}!\p"
	.string "This is our last chance to show HOENN\n"
	.string "what we as TEAM AQUA can do!\p"
	.string "{AUTO_SCROLL 1}Go make the BOSS proud!!{PAUSE 40}\n"
	.string "{AUTO_SCROLL 0}{FONT 5}(and y'know… make my job easier for me…)\p"
	.string "$"

gText_Intro_SwitchingExplanation::
	.string "{SPEAKER NAME_NONE COLOR_NORMAL}{PAUSE 20}{FONT_NORMAL}This game has two protagonists, to\n"
	.string "ensure that you have twice the fun!\p"
	.string "Press the {COLOR RED}R button{COLOR DARK_GRAY} now to\n"
	.string "switch protagonists."
	.string "$"

gText_Intro_SwitchingConfirmation::
	.string "That's it!!! Thats the {COLOR RED}R button{COLOR DARK_GRAY}!!!!!\p"
	.string "This button will be very important for\n"
	.string "solving the many puzzles in your way.\p"
	.string "If you ever forget which button it is,\n"
	.string "remember this helpful saying:\p"
	.string "If you cant go far, {PAUSE 40}press {COLOR RED}R{COLOR DARK_GRAY}.\p"
	.string "Now, let's introduce the second player.\p"
	.string "$"

gText_Intro_SwitchingFailure::
	.string "Wrong button, buster.\p"
	.string "Press the {COLOR RED}R button{COLOR DARK_GRAY} now to\n"
	.string "switch protagonists."
	.string "$"

gText_Intro_CourtneyPlayer2_Welcome::
	.string "{SPEAKER NAME_COURTNEY COLOR_MAGMA}{FONT_NORMAL}Next GRUNT in line, please.\p"
	.string "I presume you were briefed on\n"
	.string "this mission at MAGMA HIDEOUT?\p"
	.string "No?\p"
	.string "…Of course.{PAUSE 40} TABITHA will do whatever\n"
	.string "he can to make me do his job for him.\p"
	.string "To give you a quick summary, we are\n"
	.string "at VOLCANO CANYON following reports\l"
	.string "of a LEGENDARY FIRE-TYPE POKéMON.\p"
	.string "Speaking of FIRE-TYPES, I have some\n"
	.string "wonderful news for you.\p"
	.string "No, you have not been FIRED.\p"
	.string "$"	

gText_Intro_Courtney_Welcome::
	@ fade out, fade courtney in
	.string "{SPEAKER NAME_COURTNEY COLOR_MAGMA}{FONT_NORMAL}Next GRUNT please.\p"
	.string "Sorry for the wait. The loudmouth at\n"
	.string "the TEAM AQUA check-in made me want\l"
	.string "to hit her with a rock.\p"
	.string "Violent urges have been surpressed.{PAUSE 40}\n"
	.string "For now.\p"
	.string "You heard what she said, right?\p"
	.string "As much as I loathe to say it, most of\n"
	.string "the details in her speech were correct.\p"
	.string "The only amendment I can make is the\n"
	.string "reports of the LEGENDARY POKéMON in\l"
	.string "the depths of VOLCANO CAVERN prove\l"
	.string "without a doubt that it is a FIRE-type.\p"
	.string "Speaking of FIRE-TYPES, I have some\n"
	.string "wonderful news for you.\p"
	.string "No, you have not been FIRED.\p"
	.string "$"	

	@ enter numel, stage middle
gText_Intro_Courtney_MainSpeech::
	.string "{SPEAKER NAME_COURTNEY COLOR_MAGMA}No other POKéMON in this world makes\n"
	.string "a better partner than NUMEL.\p"
	.string "In addition to being the most adorable\n"
	.string "POKéMON ever, NUMEL can help you climb\l"
	.string "rocky walls to reach areas that are\l"
	.string "normally inaccesible on foot.\p"
	.string "To be quite honest, I wish I was also\n"
	.string "provided a NUMEL today.\p"
	.string "I have been looking for a sixth NUMEL\n"
	.string "to join my party, but I have been too\l"
	.string "busy with my work lately to dedicate\l"
	.string "the time to catching another.\p"
	.string "Such is the life of a TEAM MAGMA ADMIN.\p"
	.string "$"

gText_Intro_Courtney_MainSpeechPt2::
	.string "{SPEAKER NAME_COURTNEY COLOR_MAGMA}I have taken too much of your time.\n"
	.string "I apologize.\p"
	.string "Let us fill out your paperwork.\p"
	.string "$"

gText_Intro_Courtney_AndYouAre::
	.string "{SPEAKER NAME_COURTNEY COLOR_MAGMA}I will need your name and gender.\p$"

gText_Intro_Courtney_BoyOrGirl::
	.string "Your gender, please?$"

gText_Intro_Courtney_WhatsYourName::
	.string "And your name?$"

gText_Intro_Courtney_SoItsPlayer::
	.string "{SPEAKER NAME_COURTNEY COLOR_MAGMA}{PLAYER}{KUN} is correct?\p$"

gText_Intro_Courtney_YourePlayer::
	.string "{SPEAKER NAME_COURTNEY COLOR_MAGMA}Thank you, {PLAYER}{KUN}.\p$"

gText_Intro_Courtney_AreYouReady::
	.string "{SPEAKER NAME_COURTNEY COLOR_MAGMA}You and NUMEL will find the\n"
	.string "LEGENDARY POKéMON below.\p"
	.string "You may attempt to capture it, but\n"
	.string "that is not a task expected of you.\p"
	.string "Simply subduing it is acceptable.\p"
	.string "You are not allowed to leave under any\n"
	.string "circumstances until the job is done.\p"
	.string "If you find yourself in a bind,\n"
	.string "find someone nearby to help you.\p"
	.string "Take advantage of the TEAM AQUA\n"
	.string "GRUNTS if you must.\p"
	.string "I wish you the best of luck.{PAUSE 40}"
	.string "$"
