@ Starting from here, these movements are considered
@ 'safe' (won't put follower into a Pokeball)
Common_Movement_FollowerSafeStart::
Common_Movement_QuestionMark:
	emote_question_mark
	step_end

Common_Movement_ExclamationMark:
	emote_exclamation_mark
	step_end

Common_Movement_Delay48:
	delay_16
	delay_16
	delay_16
	step_end

Common_Movement_FacePlayer:
	face_player
	step_end

Common_Movement_FacePlayer2:
	face_player_2
	step_end

Common_Movement_FaceAwayPlayer:
	face_away_player
	step_end

Common_Movement_FaceOriginalDirection:
	face_original_direction
	step_end

Common_Movement_WalkInPlaceFasterLeft::
	walk_in_place_faster_left
	step_end

Common_Movement_WalkInPlaceFasterUp::
	walk_in_place_faster_up
	step_end

Common_Movement_WalkInPlaceFasterRight::
	walk_in_place_faster_right
	step_end

Common_Movement_WalkInPlaceFasterDown::
	walk_in_place_faster_down
	step_end

Common_Movement_FaceRight::
	face_right
	step_end

Common_Movement_FaceLeft::
	face_left
	step_end

Common_Movement_FaceDown::
	face_down
	step_end

Common_Movement_FaceUp::
	face_up
	step_end

Common_Movement_WalkInPlaceDown::
	walk_in_place_down
	step_end

Common_Movement_WalkInPlaceLeft::
	walk_in_place_left
	step_end

Common_Movement_WalkInPlaceRight::
	walk_in_place_right
	step_end

Common_Movement_WalkInPlaceUp::
	walk_in_place_up
	step_end

Common_Movement_WalkInPlaceFastDown::
	walk_in_place_down
	step_end

Common_Movement_WalkInPlaceFastLeft::
	walk_in_place_left
	step_end

Common_Movement_WalkInPlaceFastRight::
	walk_in_place_right
	step_end

Common_Movement_WalkInPlaceFastUp::
	walk_in_place_up
	step_end

@ End of follower-safe movements
Common_Movement_FollowerSafeEnd::
	step_end
	
Common_Movement_WalkUp5::
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	step_end

Common_Movement_WalkUp6:
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	step_end

Common_Movement_WalkUp4:
	walk_up
	walk_up
	walk_up
	walk_up
	step_end

Common_Movement_Delay32:
	delay_16
	delay_16
	step_end

Common_Movement_WalkUp::
	walk_up
	step_end

@ Unused
Common_Movement_WalkUp2::
	walk_up
	walk_up
	step_end

@ Follower NPC
Common_Movement_WalkUpSlow::
	walk_slow_up
	step_end

Common_Movement_WalkDownSlow::
	walk_slow_down
	step_end

Common_Movement_WalkRightSlow::
	walk_slow_right
	step_end

Common_Movement_WalkLeftSlow::
	walk_slow_left
	step_end

Common_Movement_WalkDown::
	walk_down
	step_end

Common_Movement_WalkRight::
	walk_right
	step_end

Common_Movement_WalkLeft::
	walk_left
	step_end

Common_Movement_WalkUpFast::
	walk_fast_up
	step_end

Common_Movement_WalkDownFast::
	walk_fast_down
	step_end

Common_Movement_WalkRightFast::
	walk_fast_right
	step_end

Common_Movement_WalkLeftFast::
	walk_fast_left
	step_end

Common_Movement_WalkUpFaster::
	walk_faster_up
	step_end

Common_Movement_WalkDownFaster::
	walk_faster_down
	step_end

Common_Movement_WalkRightFaster::
	walk_faster_right
	step_end

Common_Movement_WalkLeftFaster::
	walk_faster_left
	step_end

Common_Movement_RunLeft::
	player_run_left
	step_end

Common_Movement_RunUp::
	player_run_up
	step_end

Common_Movement_RunRight::
	player_run_right
	step_end

Common_Movement_RunDown::
	player_run_down
	step_end

Common_Movement_RideWaterCurrentDown::
	ride_water_current_down
	step_end

Common_Movement_RideWaterCurrentUp::
	ride_water_current_up
	step_end

Common_Movement_RideWaterCurrentLeft::
	ride_water_current_left
	step_end

Common_Movement_RideWaterCurrentRight::
	ride_water_current_right
	step_end

Common_Movement_JumpSpecialDown::
	jump_special_down
	step_end

Common_Movement_JumpSpecialUp::
	jump_special_up
	step_end

Common_Movement_JumpSpecialLeft::
	jump_special_left
	step_end

Common_Movement_JumpSpecialRight::
	jump_special_right
	step_end
	
Common_Movement_Jump2Down::
	jump_2_down
	step_end

Common_Movement_Jump2Up::
	jump_2_up
	step_end

Common_Movement_Jump2Left::
	jump_2_left
	step_end

Common_Movement_Jump2Right::
	jump_2_right
	step_end

Common_Movement_JumpDown::
	jump_down
	step_end

Common_Movement_JumpUp::
	jump_up
	step_end

Common_Movement_JumpLeft::
	jump_left
	step_end

Common_Movement_JumpRight::
	jump_right
	step_end

Common_Movement_RockSmashBreak::
	rock_smash_break
	step_end
